---
swagger: 2.0
info:
  title: test
  description: test apicurio
  contact:
    name: oren Source
    url:
    email:
  version: 1.0.0
paths:
  /test:
    get:
      description: get test
securityDefinitions:
  Authorization:
    type: apiKey
    name: Authorization
    in: header
